all solutions
js-tasks-ru/jsbasic-20240321_maksimrudakov pull request #3
Opened 2024-03-24 12:48 UTC by MaksimRudakov1601

2024-03-24 12:49 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2024-03-25 14:19 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-03-25 14:25 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2024-03-25 14:32 UTC, MaksimRudakov1601 commented
Finished 2 module

2024-03-26 16:20 UTC, SinimaWath requested changes

2024-03-26 16:20 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  return (name != null && name.length > 3 && !name.includes(" ")) ?
Если результат операции boolean, то if не нужен:
`return name != null && name.length > 3 && !name.includes(" ")`

2024-03-26 16:20 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  let strLowered = str.toLowerCase();
nit: это скорее `const`

2024-03-30 10:47 UTC, SinimaWath approved these changes
все круто

2024-03-30 10:48 UTC, merged